version: ~> 1.0
language: scala
scala:
  - 2.13.1

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

jobs:
  include:
    - stage: drop-travis-caches
      script:
        - rm -rf $HOME/.m2
        - rm -rf $HOME/.ivy2/cache
        - rm -rf $HOME/.sbt/boot
        - rm -rf $HOME/.sbt/launchers
        - rm -rf $HOME/.cache/coursier
        - rm -rf $HOME/.jabba
        - rm -rf $HOME/.gradle
    - stage: check
      name: "sbt & Paradox (JDK 8)"
      script: sbt test docs/paradox
      env: TRAVIS_JDK=adopt@1.8-0

    - name: "sbt & Paradox (JDK 11)"
      script: sbt test docs/paradox
      env: TRAVIS_JDK=adopt@1.11-0

    - name: "Maven (JDK 8)"
      ## set name to "hello-world-grpc" and accept all other defaults (--force)
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test
      env: TRAVIS_JDK=adopt@1.8-0

    - name: "Maven (JDK 11)"
      ## set name to "hello-world-grpc" and accept all other defaults (--force)
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test
      env: TRAVIS_JDK=adopt@1.11-0

    ## Gradle builds will fail: https://github.com/akka/akka-grpc/issues/1034
    - name: "Gradle (JDK 8)"
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build
      env: TRAVIS_JDK=adopt@1.8-0

    - name: "Gradle (JDK 11)"
      script: sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build
      env: TRAVIS_JDK=adopt@1.11-0

stages:
  - name: check
  - name: drop-travis-caches
    if: env(RUN_DROP_TRAVIS_CACHES_STAGE) = true

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.gradle
    - $HOME/.jabba
    - $HOME/.m2/repository

notifications:
  email:
    recipients:
      - akka.official@gmail.com
    on_success: never
    on_failure: always
    if: (branch = master OR branch = main)
