language: scala
scala:
  - 2.12.6

jdk:
  - oraclejdk8

# don't seem to work - perhaps due to agent version?
#  - oraclejdk10
#  - oraclejdk11

script:
 - sbt test docs/paradox

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.gradle
