name: Cron builds

on:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check:
    name: JDK ${{ matrix.jdkVersion }}
    if: github.repository == 'akka/akka-grpc-quickstart-java.g8'
    strategy:
      matrix:
        jdkVersion: ["adopt@1.8.0", "adopt@1.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdkVersion }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdkVersion }}

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: sbt & paradox
        run: |-
          sbt test docs/paradox

      - name: Maven
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  mvn test

      - name: Gradle
        run: |-
          sbt new file://$PWD --name=hello-world-grpc --force && pushd hello-world-grpc &&  ./gradlew --console=plain build

      - name: Email on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Failed: ${{ github.workflow }} / ${{ github.job }}"
          to: akka.official@gmail.com
          from: Akka CI (GHActions)
          body: |
            Job ${{ github.job }} in workflow ${{ github.workflow }} of ${{github.repository}} failed!
            https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
